### ISSUE TITLE
Import Aware?

### ISSUE THREAD

**Issue by jamiejackson** [gossi/eclipse-transpiler-plugin#12]
Say I have a master.less, which is a file that imports a bunch of other LESS files. This master.less should transpile to masters.css.

* If I modify, master.less, it works as I'd expect: The change is detected and master.css is transpiled to master.css
* If I modify, import.less (a LESS file imported by master.less), nothing seems to happen; the master.css is not transpiled.

What's wrong?
* My expectations?
* My configuration?
* The plugin doesn't support detection of modified import files?

**Comment by gossi** [comment]
Closed in favor of #13 which provides a strategy for you are looking for.
